Lab 6
uofu-emb/lab06_corey_miguel pull request #1
Opened 2024-11-17 18:19 UTC by corey-buchanan

2024-11-18 16:15 UTC, warnerjon12 requested changes
Overall looks good, but please remove .DS_Store and write tests for activity 0

2024-11-18 16:15 UTC, warnerjon12 commented on .DS_Store
This file should not have been committed. I usually run `git status` prior to committing just to make sure I am committing what I think I am, especially if using `git commit -a`

2024-11-18 16:15 UTC, warnerjon12 commented on src/hello_freertos.c
This looks good, but I would add tests to verify that this does what you think it does for binary and mutex semaphores, respectively. You could probably refactor this code into test code by replacing (or supplementing) the print statements with something you can check and making the supervisor task a test function.

2024-12-06 20:44 UTC, Mgomez-01 commented on .DS_Store
removed

2024-12-06 21:25 UTC, chasegriswold approved these changes
Looks good to me, and CICD is passing. I think it's ready to merge.

2024-12-06 21:26 UTC, merged